### ISSUE TITLE
Invalid Dockerrun.aws.json version

### ISSUE THREAD

**Issue by kazysgurskas** [awslabs/eb-docker-nginx-proxy#1]
Getting

```
INFO  [26070] - [Application update/AppDeployStage0/AppDeployPreHook/03build.sh] : Activity execution failed, because: Invalid Dockerrun.aws.json version, abort deployment (ElasticBeanstalk::ExternalInvocationError)
caused by: Invalid Dockerrun.aws.json version, abort deployment (Executor::NonZeroExitStatus)
```

In the `eb-activity.log`. Enclosing version number in double-quotes does not help. Could it have something to do with my environment? I left mostly everything default.

**Comment by abhiksingh** [comment]
Seems like you answered you own question at https://forums.aws.amazon.com/thread.jspa?threadID=221802. We are currently working on adding support for the multicontainer platform in eu-central-1.
